spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:h2:mem:///devdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:    
---
spring:
  profiles: test
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres
logging:
  level:
    org.springframework.data.r2dbc: Debug
---
spring:
  profiles: prod
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/proddb
    username: postgres
    password: postgres

  logging:
    level:
      org.springframework.data.r2dbc: Debug

 
  